### ISSUE TITLE
Add support for Ledger hardware wallet 

### ISSUE THREAD

**Issue by michaeltomasik** [LiskHQ/lisk-hub#1101]
### Expected behaviour
Add support for Ledger Nano S hardware wallet 
https://taikonauten.atlassian.net/browse/L20-446
https://taikonauten.invisionapp.com/d/main/#/console/12665756/311509545/inspect

https://taikonauten.invisionapp.com/d/main/#/console/12665756/311509544/inspect

https://taikonauten.invisionapp.com/d/main/#/console/12665756/311509546/inspect

https://taikonauten.invisionapp.com/d/main/#/console/12665756/312491170/inspect

Ledger Illustration: https://taikonauten.atlassian.net/browse/L20-446

Confirmation in send process https://taikonauten.invisionapp.com/d/main/#/console/12665756/284010013/preview

#### Login
- Login page should detect connected hardware wallet and display a link
<img width="1395" alt="screen shot 2018-12-11 at 12 30 45" src="https://user-images.githubusercontent.com/1254342/49797741-a2734e00-fd40-11e8-9079-14757f5cb010.png">

https://taikonauten.invisionapp.com/d/main/#/console/12665756/311509547/preview
- If Lisk app is not open on the HW, attempt to access it will first show this screen
![screen shot 2018-10-10 at 16 49 33](https://user-images.githubusercontent.com/1254342/46745129-bfda5c00-ccac-11e8-9a47-b81839632dcd.png)
- After opening the app on the HW wallet it should go to a page that lists accounts found on the HW wallet and allows to add a new one
![screen shot 2018-10-10 at 16 48 34](https://user-images.githubusercontent.com/1254342/46745105-b650f400-ccac-11e8-9adf-cd22bcb6c343.png)
- The accounts page allows adding only one empty account at a time, another account can me added only after some LSK tokens are sent to the previous account.
- A new account can be labeled by the user and the label is stored in localStorage.
- Edit option should allow to change labels

- When HW wallet is disconnected, user is logged out and a modal with explanation is displayed
<img width="1397" alt="screen shot 2018-12-11 at 12 31 44" src="https://user-images.githubusercontent.com/1254342/49797775-c33ba380-fd40-11e8-89d0-1b284c1445b3.png">

#### Send
- Send transaction process asks for confirmation on the HW wallet in the "confirmation step"
- Declining the transaction on the HW wallet goes to error step. The error step has options to Retry or Cancel (Okay).
- Retry goes to the first step and keeps Address, amount, and reference.
- Cancel (Okay) goes to the first step and clears Address, amount, and reference.
![screen shot 2018-11-01 at 15 35 17](https://user-images.githubusercontent.com/1254342/47858206-cb243180-ddeb-11e8-8e3e-54a2576b7f29.png)

#### Vote
- Vote transaction process asks for confirmation on the HW wallet in the "confirmation step" and works like send above.

#### Other transaction types
- Second passphrase registration is disabled on HW wallet account
- Delegate registration is disabled on HW wallet account
- Sign message process asks for confirmation on the HW wallet instead of the "passphrase step"

### Subtasks

- Investigate HW wallet PR in Nano, how to test * medium

- Implement list of accounts on the hw *hard
- Implement login to hardware wallet account *medium
- Support send and vote transaction *medium

- Support sign message  *medium

**Comment by hirishh** [comment]
Hello @michaeltomasik 

I think it's time to open a discussion about some common implementation we need to agree. 
I will create a PR on lisk-nano with the integration I'm coding. 

There are some key-points we need to discuss.

### Delegate Registration
To register a delegate is a common transaction and is possible with Hardware Wallet as I've shown on my demo about Ledger Integration ([Youtube Video](https://www.youtube.com/watch?reload=9&v=IdTGliuMBJ0)) BUT at the moment there is no way that a delegate can forge with HW because of the blocks signing process. There are some solution we are discussing with @vekexasia but it's hard topic. 

**Problem**: Is NOT possible to forge with a delegate registered from an HW address
**Solution**: Not yed defined (just some hypothesis)
**Mitigation**: Disable Delegate registration functionality for HW in order to avoid people losing fees.

### Address Discovery
A single Hardware Wallet (Ledger, Trazor or any others) can create infinite addresses for a single coin. It means that you can have more than 1 Lisk ID/Account on your HW thanks to **path derivation**.
I'm implementing Address Discovery in order to show to the user all the initialized accounts on his Hardware Wallet and allow to create more. About this topic we need to agree on common rules so the address discovery can be the same on every product (nano, hub, my fork, etc..):

- An account is initialized when there is at least 1 transaction
- You can Initialize a new account X only if account X-1 is initialized.

If we agree on these 2 simple rules, the Address Discovery will be easy to implement and it will be the same everywhere

### Second Passphrase Registration
Lisk allow to register a second passphrase in order to make lisk accounts more secure. There is no limitation and is definitely possible with HW. But we need to agree on some details in order to be aligned with a common solution. Is possible to select another account inside the HW that will be used as second passphrase in order to avoid online created passhrases.

**Problem**: How to select the second passphrase
**Proposed Solution**:  Fow HW accounts, the second passphrase will be a "Personal PIN". This PIN is a number (like bank account PIN). We use this PIN to calculate an offset and select a particular account from the HW

Example: Let's say we are logged in with Account X on our HW and we want to secure this account by registering a second passhprase:

- Lisk Hub will ask for a personal PIN (numeric). 
- An offset is calculated like this: PIN + 1e5 = Y
- Account Y is selected from the HW and will be used as second passhprase

It must be clear that if user forget the PIN, it will be impossible to select the correct account Y.

This is what I'm implementing and what I'm going to deliver to lisk-nano in the coming weeks.
For any question and information, I'm here to help.

Best,

hirish

PS: Could you add me to LiskHQ github organization so I can provide the PR on lisk-nano?

**Comment by slaweet** [comment]
Hello @hirishh,
Thank you for raising the points here. 
We'll discuss it in LiskHQ to align internally on how we want this with Lisk Hub, but at the moment your proposed solutions seem reasonable to me. 

AFAIK you don't need to be added LiskHQ to open PR on Nano. And I'm really curious to see the implementation in nano, do you have it somewhere in Github?

Thanks
Vít

**Comment by michaeltomasik** [comment]
Hi @hirishh,
just ask Oliver to send you an invitation to an organization, let me know when you get an invite.

**Comment by hirishh** [comment]
Preview of the account discovery:

![image](https://user-images.githubusercontent.com/7662810/43416933-f10693da-9439-11e8-8177-329c6e046882.png)

**Comment by hirishh** [comment]
For this integration (I will provide PR in a few days) I had to build my own raw transactions. I couldn't use Lisk-Elements for this since passphrase and signing process is mandatory. So I've opened this Issue on lisk-elements: https://github.com/LiskHQ/lisk-elements/issues/768

**Comment by alepop** [comment]
@slaweet @hirishh @michaeltomasik after that this https://github.com/trezor/connect/pull/194 will be merged you can start to integrate `Trezor` in Hub/Nano

**Comment by alepop** [comment]
https://github.com/trezor/connect/pull/197 merged. Next version of `Trezor connect` will be with Lisk support.

**Comment by slaweet** [comment]
@hirishh I discussed your three proposals (Delegate Registration, Address Discovery, Second Passphrase Registration) with Max. 
We agreed to Disable Delegate registration and do Address Discovery as you proposed.

We're not clear about how much extra protection adds the second passphrase PIN. It seems like it would be quite easy to brute force. When I know the first public key, I can get the second public key from the blockchain, so it would be just running account discovery from offset 1e5 and comparing the public key. I don't know how fast this is, but I would expect at least thousands of accounts per second, so a 4-digit pin would be very weak. Of course, we can require a longer PIN, but how long should it be? Do you have any idea how fast is the account discovery?  

So far we are in favor of disabling Second Passphrase Registration in hardware wallet.

**Comment by hirishh** [comment]
@slaweet your thoughts are right about brute-forcing the PIN. PublicKey derivations from Ledger are almost instant, so with a 10-lines script and physical access to the Ledger, the PIN can be exploited. Ledger has is personal PIN and I agree that having second passphrase (PIN) is adding too much complexity compared to "extra protection".

I'm ok to disable the "PIN" feature and stay clean with the use and implementation of the ledger. I will push the changes on my PR on lisk-nano.

Best

**Comment by karek314** [comment]
Enabling second passphrase with hardware wallet is literally 0 effort. It's just different path. Technically it lifts security a bit.

https://github.com/LiskHQ/lisk-hub/issues/1192
https://github.com/trezor/trezor-core/issues/326

Working example as CLI
https://github.com/karek314/LiskTrezor-CLI-wallet-manager

**Comment by hirishh** [comment]
Yes, that's why I think I will publish it as an optional feature in my Liskish Wallet
