### ISSUE TITLE
Autosuggest should show error message when no results found.

### ISSUE THREAD

**Issue by faival** [LiskHQ/lisk-hub#1193]
### Expected behaviour

In the cases where activePeerSet was not called, calls to autosuggest search will respond with failure.

In such cases a default 'No results found' should appear in the dropdown. 

Alternatively find a better way to distinguish: 

- peers connectivity down
- no results found

**Comment by slaweet** [comment]
After giving this some thought, I would say that the logout should clear the account, but not the active peer. 
We are already setting the active peer on starting the app:
https://github.com/LiskHQ/lisk-hub/blob/cd367e3a4f567807c2d538fa4b3cb1bdc83dcd8a/src/store/middlewares/peers.js#L17-L18
It should however use last active network, instead of always Mainnet:
https://github.com/LiskHQ/lisk-hub/blob/cd367e3a4f567807c2d538fa4b3cb1bdc83dcd8a/src/store/middlewares/peers.js#L10

**Comment by Efefefef** [comment]
This one should be not a bug but enhancement with thoroughly specified requirements

**Comment by Efefefef** [comment]
This issue is a result of the integration of two features: logged out dashboard and not-saving accounts anymore. Therefore it is not a product bug but unforeseen circumstances which were not specified. Specification should come then first
