### ISSUE TITLE
Find a better place for Cypress link

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1382]
### Current behaviour
Cypress post a link to the test results only in the Jenkins console output.
E.g.  https://dashboard.cypress.io/#/projects/1it63b/runs/454 in https://jenkins.lisk.io/job/lisk-hub/job/development/335/consoleFull

### Expected behaviour
There should be an easy way to get to the cypress link

- One option would be to post cypress results to GitHub PR checks with the link in "details":
![screen shot 2018-10-23 at 11 03 07](https://user-images.githubusercontent.com/1254342/47349170-52b6c580-d6b3-11e8-8619-d9f68f849ffb.png)

- Another option would be to add it to Jenkins build report:
![screen shot 2018-10-23 at 11 07 25](https://user-images.githubusercontent.com/1254342/47349543-20f22e80-d6b4-11e8-9f52-4e2fbfd40e3e.png)

Either would be fine, depends on how much work each is.

**Comment by Efefefef** [comment]
Since cypress still doesn't have their own github integration I think that we can use guthub statuses api for implementing the task:
https://developer.github.com/v3/repos/statuses/
Idea is to post the pending status before e2e tests run (or maybe at the beginning of the build process)
And to post the result getting the data from the 
`npm run cypress:run -- --record` output
0 if everything went fine - "state": "success",  "description": "All e2e tests passed!",
not 0 if test errored - "state": "failure",  "description": "Some e2e tests failed",
"context": "Cypress e2e test results"
for "target_url" we should extract the link from this line 
`Recorded Run: https://dashboard.cypress.io/#/projects/1it63b/runs/448`
@fchavant may I ask you for help implemeting that?

**Comment by fchavant** [comment]
@Efefefef can do

**Comment by Efefefef** [comment]
@fchavant There is a problem now. Every time build fails e2e status is shown as red.
e2e status should be red only if the reason of failure were e2e tests.
And when rerunning build e2e status should be set to pending or cleared.

**Comment by fchavant** [comment]
@Efefefef can you link such a build?

**Comment by Efefefef** [comment]
@fchavant PM you

**Comment by slaweet** [comment]
Fixed in https://github.com/LiskHQ/lisk-hub/pull/1425
