### ISSUE TITLE
Set discard old builds property in Jenkinsfile

### ISSUE THREAD

**Issue by Nazgolze** [LiskHQ/lisk-hub#1488]
Old builds are staying around forever on Jenkins, causing us to run out of disk space
### Steps to reproduce

1. build the development branch about 30 times

### Actual result
old builds live forever

### Expected result
needs manual intervention

### Version
1.6.0, 1.7.0

**Comment by slaweet** [comment]
@Nazgolze how do you define an old build?
I see two options:
- Older than X weeks
- Keep last N builds

What value can be X and N above?
X should be at least 2
N so big that we have builds last 2 weeks of builds

Why? Because when there is some non-urgent problem in Jenkins, we create a ticket to fix it with link to the build and by the time we get to work on it, the link wouldn't work anymore.

**Comment by Nazgolze** [comment]
Closed by #1490
