### ISSUE TITLE
Send: Confirm step: An error occoured while rendering this page

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#1604]
### Steps to reproduce

1. Got o wallet->send
1. Fill mandatory fields
1. Next

### Actual result

An error occoured while rendering this page
`The above error occurred in the <Confirm> component:
    in Confirm (created by I18n)
    in I18n (created by Translate(Confirm))
    in Translate(Confirm) (created by Connect(Translate(Confirm)))
    in Connect(Translate(Confirm)) (created by Send)
    in div (created by MultiStep)
    in MultiStep (created by Send)
    in div (created by Send)
    in div (created by Send)
    in div (created by Box)
    in Box (created by Send)
    in Send (created by I18n)
    in I18n (created by Translate(Send))
    in Translate(Send) (created by Connect(Translate(Send)))
    in Connect(Translate(Send)) (created by Route)
    in Route (created by CustomRoute)
    in ErrorBoundary (created by I18n)
    in I18n (created by Translate(ErrorBoundary))
    in Translate(ErrorBoundary) (created by CustomRoute)
    in main (created by CustomRoute)
    in CustomRoute (created by I18n)
    in I18n (created by Translate(CustomRoute))
    in Translate(CustomRoute) (created by Connect(Translate(CustomRoute)))
    in Connect(Translate(CustomRoute)) (created by Route)
    in Route (created by withRouter(Connect(Translate(CustomRoute))))
    in withRouter(Connect(Translate(CustomRoute))) (created by App)
    in Switch (created by App)
    in div (created by App)
    in section (created by App)
    in main (created by App)
    in section (created by OfflineWrapper)
    in OfflineWrapper (created by Connect(OfflineWrapper))
    in Connect(OfflineWrapper) (created by App)
    in App
    in I18nextProvider
    in Router (created by HashRouter)
    in HashRouter
    in Provider
`

**Comment by osvaldovega** [comment]
The problem with this issue was related old node modules version.
@renatomassao was working on this commit - **1fc23978dae81463e1fe5ec1f23fe4f99ff0231f** (♻️ Update bignumber.js .round(0) to .decimalPlaces(0)) and he made the change, and that was because the old version of bignumbers do not use any more round function.

So I had to delete my node modules folder and run npm install again and now everything is working as should be.

Problem is fix by update the deleting and installing node modules again.
