### ISSUE TITLE
Allow to store and send BTC

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1831]
### Motivation
We have decided to add additional tokens to our wallet in order to open new opportunities to attract a bigger user base. Features implemented must make it easier for users currently holding other tokens, starting with BTC, to easily exchange their tokens to LSK and get the benefits of using this Platform.

### Account identity
Since both platforms are using bip39 standard based mnemonic passphrases, we can use the same passphrase and let users interact with their Lisk account using an existing BTC-originated passphrase and vice-versa.

### The user journey specification
- The header and navigation must be token independent to prevent confusions.
- The users must be able to change the active token in the wallet page as well as in Send and bookmarks.
- Transaction items shown in the wallet must correspond to the active page.
- Clicking on each transaction item must navigate the users to the transaction detail page.
- The active token must be clearly understood in the transaction details page.
- The users must be able to click on the recipient/sender address (only the one which is not the currently signed-in account) and navigate to its dedicated wallet page.
- Users must not be able to change the active token in transaction details page or other accounts' wallet page; as it invalidates the content of the current page and forces an unintended redirection/navigation.
- Changing the active token in the Send page must redirect to the users to the first step of the send page and reset the form. as it invalidates the previous steps.
- The users must be able to choose low or high transaction fee while sending BTC tokens.
- Since the BTC blockchain doesn't provide message feature on its transactions, this input must not be visible on the send page for BTC transactions.
- Users must be able to filter their transactions based on reasonable properties (not available in MVP).
- Users must see their latest active account when they sign in again.
- Users need a brief introduction about the BTC feature. This involves a congrats message as well as a tooltip for changing the active token.
- The bookmark list should allow the users to see the followed/bookmarked accounts for all the tokens, as well as for an individual token.

## Questions to explore
- Should we briefly mention BTC in the "Create new account" process? Or what other ways can we use for discoverability of that feature?
- How to adapt the launch protocol to work with existing BTC wallets.

**Comment by Efefefef** [comment]
@reyraa 
1. Should the BTC/LSK switcher be available while connected to testnet or devnet?
1. We will need to run local bitcoin devnet for testing purposes. We have to think how network switching will look and work beforehand
1. It is not clear what this point means
`Users must not visit the send/message step while sending BTC token since this blockchain does not support such a feature.` mean
1. Are we going to show LSK specific widgets on the dashboard when in BTC mode? As it is said that user will be able to change token in bookmarks which are located on the dashboard, not on the wallet, I expect the mode change affects every page

**Comment by reyraa** [comment]
@Efefefef 
1. For testate Yes. but for devnet, the only need I see is for running the e2e tests. which makes thinks a lot slower at the moment. I'd suggest skipping this for now.
2. If we don't consider the devnet, this shouldn't be an issue.
3. I should have written "message input", the terminology is based on the idea of having on input at a step. 
![Screenshot 2019-04-16 at 08 26 16](https://user-images.githubusercontent.com/666685/56187020-a7fbe000-6021-11e9-874c-971c719e7abf.png)
4. Some designs in final and available on our InVision and Zeplin channels, the dashboard followed account is one of them. after discussions with the designers this is changed in order to simplify the UX, now each address is stored and shown separately for each token. I've updated the epic description.

https://netguru.invisionapp.com/share/D2RJLTY8E57#/screens/358081871

**Comment by Efefefef** [comment]
@reyraa ok got it
