### ISSUE TITLE
Align the design of Delegates Page

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#2167]
![image](https://user-images.githubusercontent.com/6704159/59908547-f48edd80-940d-11e9-92c9-9b0bae4fe88a.png)

![image](https://user-images.githubusercontent.com/6704159/59906766-cb6c4e00-9409-11e9-92e4-c9b83770d9b4.png)

![image](https://user-images.githubusercontent.com/6704159/59907054-78df6180-940a-11e9-8b5b-fec46976b8bf.png)

LSK signs - talk to Yashar
![image](https://user-images.githubusercontent.com/6704159/59906919-24d47d00-940a-11e9-98fe-305ee62853bf.png)

![image](https://user-images.githubusercontent.com/6704159/59908500-d88b3c00-940d-11e9-8bff-c26825f99ec8.png)

🐛 Register as delegate available while logged in with HW

**Comment by slaweet** [comment]
- I didn't implement the third tooltip as I didn't find a copy for it. Now all the tooltips or gone from design files. Is it intentional @reyraa?
- The `3/101` is `24px` in design, but in the styleguide https://projects.invisionapp.com/d/main#/console/17570736/365298851/inspect
we have only `30px` or `18px` for headings, so I check with Dominic and implemented `30px , should be updated in design.
