### ISSUE TITLE
Align the design of Send page

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#2170]
![image](https://user-images.githubusercontent.com/6704159/59907558-a973cb00-940b-11e9-9277-5501a5e22313.png)

Box wrapper
![image](https://user-images.githubusercontent.com/6704159/59907591-bbee0480-940b-11e9-9fd6-5b992003686b.png)

![image](https://user-images.githubusercontent.com/6704159/59907623-cdcfa780-940b-11e9-8c14-0e0ee4f190eb.png)

There should be no jumping when click into message field. Byte leftover indicator should be always visible and working (right now doesn't work).
![image](https://user-images.githubusercontent.com/6704159/60020132-b0ab0b00-968f-11e9-93be-7b64ad91ca36.png)

When you enter more than 64bytes the circle should turn to red exclamation mark

All the validation errors should stay when click outside of the input

**Comment by slaweet** [comment]
> ![image](https://user-images.githubusercontent.com/6704159/59907623-cdcfa780-940b-11e9-8c14-0e0ee4f190eb.png)

Solved in https://github.com/LiskHQ/lisk-hub/pull/2150/commits/37b3492121a778bf8e7e7a272beba6aa314030cd

**Comment by massao** [comment]
> There should be no jumping when click into message field. Byte leftover indicator should be always visible and working (right now doesn't work).
> ![image](https://user-images.githubusercontent.com/6704159/60020132-b0ab0b00-968f-11e9-93be-7b64ad91ca36.png)
> 
> When you enter more than 64bytes the circle should turn to red exclamation mark
> 
> All the validation errors should stay when click outside of the input

For this one, there are two main problems that must be solved:
- When changing the amount or the reference field, there are two functions updating the state, the `onInputChange` and the `validateAmountAndReference`, the best solution would be to refactor the whole form component, but for now we should be good, just updating the setState to use a function, so React can understand that should consider the values from previous setState calls in the same cycle;
  - This causes the counter to not be updated and the error state getting messed up, because the previous setState is being discarded;
- The feedback is only shown when the input is focused, which is causing also the problem with the field losing the line counter, because it's using the `onFocus` and `onBlur` the markup should be restructured in a way that the  feedback is in the same container as the input, so it could be shown or hidden with only css like `input:focus ~ .feedback`;
