### ISSUE TITLE
Investigate better approaches to implement transaction filters

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-hub#2244]
In order for the team to discuss issues with the current implementation and propose alternatives, we need to prepare a document explaining the current state and the first draft of the proposal.

**Comment by slaweet** [comment]
The conclusion of the investigation is the following.

`addFilter` action is dispatched in `src/components/transactions/explorerTransactions/explorerTransactions.js` and `src/components/transactions/walletTransactions/walletTransactions.js`. 

- `src/components/transactions/explorerTransactions/explorerTransactions.js` was updated in https://github.com/LiskHQ/lisk-hub/pull/2278 not to use `addFilter` anymore.
- `src/components/transactions/walletTransactions/walletTransactions.js` can be updated not to use `addFilter`, because the filter value is also stored in `transactions` reducer. 


Or alternatively `walletTransactions.js` ca be upadted to use `withData` HOC like `explorerTransactions.js` does. This would be a bit more work.
