### ISSUE TITLE
Request BTC - Address font is broken and small design inconsistency

### ISSUE THREAD

**Issue by imdominic** [LiskHQ/lisk-hub#2309]
### Steps to reproduce

1. Open Lisk Hub.
2. Go to wallet.
3. Switch your wallet from LSK to BTC.

### Actual result
BTC Address font looks broken in the modal, font sizes and alignments somehow are not matching what was in the design.

<img width="427" alt="Screenshot 2019-08-02 at 11 51 17" src="https://user-images.githubusercontent.com/45934100/62369748-eebe0900-b530-11e9-906c-0e79db99933b.png">

### Expected result

Fix the padding for the CTA, align the font size to the style guide.

<img width="1010" alt="Screenshot 2019-08-02 at 14 28 24" src="https://user-images.githubusercontent.com/45934100/62370087-ce427e80-b531-11e9-8ab5-11bdb43ac148.png">

### Version
1.19.1

**Comment by slaweet** [comment]
Most of the problem was solved in https://github.com/LiskHQ/lisk-hub/pull/2329 as it has the same root cause, but there's still one problem: The address overflows on some screen size
![Screenshot 2019-08-12 at 09 09 09](https://user-images.githubusercontent.com/1254342/62849746-16576300-bce1-11e9-95de-fb5caa9f4739.png)
