### ISSUE TITLE
Support signing messages

### ISSUE THREAD

**Issue by robladbrook** [LiskHQ/lisk-hub#457]
### Expected behaviour
Within the Hub app, users should be able to sign a message (as they can in Nano).

### Actual behaviour
This feature is currently not supported.

@slaweet @reyraa @yasharAyari if you are able to provide details regarding where this feature should sit within Hub?

The Lisk Ascend team is happy to develop/PR the feature for Hub, but obviously would want to coordinate with you to ensure it aligns with how you'd like it to work.

**Comment by puredelta** [comment]
Any estimated time when this feature is going to be available in Lisk Hub?

**Comment by Nimbus76** [comment]
The ability for users to Sign Messages in Lisk's default wallet is especially helpful for developers.  Ascend has demonstrated the value of this feature with Ascend's Pledge System, where the Sign Message feature is used to validate users and verify account balances of pledgers without requiring transactions on the blockchain.  Additional uses include more reliable and informative community polling, secure logins, and 2FA.

**Comment by liskprocom** [comment]
In the crypto world, giving the ability to sign message with your own identity (Lisk ID), to prove who you are and offer a secure way to communicate is, I think, really essential ! 

Intigrity and non repudiation must me a standart ! 

So please, include this functionnality in the new Hub.

**Comment by slaweet** [comment]
We at LiskHQ see that signing message is important to the crypto community, but with Lisk Hub we aim to bring Lisk to the general public and we believe that we need to make Hub as simple as possible and adding sign message will add more complexity that we don't want.

You can Sign message with Lisk Nano, for now. By the time Lisk Nano is discontinued, signing message will be possible with our command line interface https://github.com/LiskHQ/lisky

**Comment by Nimbus76** [comment]
The issue there is that the CLI provides users with an even worse experience. It is not developers who need to sign messages, but the developer's users who need to. Not including the Sign Message function in Hub takes essentially takes away the usability of this feature from developers. It is the opposite of enabling blockchain creators.

**Comment by 5an1ty** [comment]
@slaweet I understand your reasoning to close this issue is that this is not a feature required by Lisk Hub's target audience. Putting this issue on low priority seems logical but outright closing it makes no sense at all.

Firstly proving ownership of an address or proving that a specific message came from a certain address is a very useful feature for numerous reasons, not just Lisk Ascend's use-case. Especially so for Lisk Hub's target audience that aren't developers (because signing a message with your private key isn't that complicated for a developer).

Secondly taking away a feature is bad UX to begin with, all we want is for the feature to just be available in Lisk-Hub under an advanced tab or toggle (whatever makes most sense UI/UX).

**Comment by hirishh** [comment]
Moreover, these features were already available and perfectly hidden prior this PR: https://github.com/LiskHQ/lisk-hub/pull/231 

So the issue here is mainly that this features should be present in lisk-hub. If normal users want to sign a message or verify a signed message you are pushing them to become developers. This is the **opposite** of "user friendly". 

That's a poor decision in my opinion.

**Comment by benfavre** [comment]
Could we possibly have an update on this and have a clear statement on what the long term goals liskHQ has on this (message signing) in Lisk-hub.
Thanks.

**Comment by slaweet** [comment]
We at LiskHQ have put more thought into this issue based on all the community feedback we've got. 

We came to the conclusion that signing a message is in the vast majority of cases something that the user is asked to do by a third party. To support that use case we want to make signing message accessible by the Lisk launch protocol. 

It would mean a link (that can optionally contain the message) created by the third party and shared with the user to click on,  e.g. lisk://sign-message?message=Here%20is%20the%20message When a user clicks on the link, it opens Lisk Hub desktop app on the "Sign message" page with a pre-filled message. 

To keep the UI clean, there would be no way to access the page from the UI without the link. 

It would work also with a link to the web Lisk Hub, e.g.: https://lisk.io/hub/#/sign-message?message=Here%20is%20the%20message

**Comment by 5an1ty** [comment]
@slaweet This is a clear and positive message that LiskHQ cares and appreciates community feedback. Thank you very much for that!

I think your proposal is a fair compromise in keeping the UI simple and providing the feature to the most obvious use cases.

One situation that might be trickier is if you as a user want to quickly prove ownership of your address to someone you are talking/chatting with. But those "power" users could still use lisky if they really wanted to.

**Comment by Nimbus76** [comment]
This sounds like a workable solution and the one-click launch and pre-filling of the message would make for a good user interface.  Hub stays clean and developers/service providers can take advantage of advanced features.

**Comment by kilkelly** [comment]
I like the idea of signing messages and happy to hear that LiskHQ will support it with the launch protocol. It's completely understandable that this feature is not readily available from Lisk Hub in order to keep a clean and simple interface. Thanks for the update @slaweet
