### ISSUE TITLE
Add nofollow / noindex to links to accounts, transactions, etc

### ISSUE THREAD

**Issue by Nazgolze** [LiskHQ/lisk-hub#475]
### Expected behaviour
Links to transactions, accounts, etc, shouldn't be indexed by search engines
### Actual behaviour
Currently, links could get indexed by search engines if someone posted a
direct link to a transaction in the hub explorer

This is analogous to https://github.com/LiskHQ/lisk-explorer/issues/444

**Comment by michaeltomasik** [comment]
"Hmmm, this is tricky. Google does follow divs in some cases. If there's a obvious "onclick='some_url'", I don't know exactly how sophisticated their crawler is, but I do know that it goes so far as to even execute javascript.
Actually, if this is true - https://www.searchenginepeople.com/blog/16094-google-javascript-crawling.html
We should already be good even without your change. I'm going to run this past Expand Online and see...
searching google for inurl:hub site:lisk.io doesn't give much, which is promising...
...Got word back from Expand Online, so far so good"
~Juan Gonzalez

Since there is no problem anymore, I'm closing this issue.
