### ISSUE TITLE
Add "export to csv" button to transaction history

### ISSUE THREAD

**Issue by kubakufel** [LiskHQ/lisk-hub#551]

**Comment by tobiaslins** [comment]
I implemented a export tool in the meantime. Would be happy to contribute if its defined!
It streams the data directly from the postgres database. 
https://github.com/tobiaslins/lisk-export

**Comment by slaweet** [comment]
Hi @tobiaslins ,
before we get to the discussion **if** we want this feature in Lisk Hub, I'd like to understand how should it work.

From Lisk Hub point of view, the feature should be in Lisk Core, because you can connect Lisk Hub to different Lisk Core instances (Mainnet, Testnet, Devnet) with different blockchain contents and the CSV export should contain the according data.

You can [open Issue on Lisk Core](https://github.com/LiskHQ/lisk/issues/new) to discuss with Core team if they will accept this feature. 

Or do you have some other way to integrate this in Hub?

**Comment by slaweet** [comment]
Closing. We can reopen if Lisk Core implements support for this.
