### ISSUE TITLE
Click on a transaction in the "Latest activity" section on the Dashboard does nothing

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk-hub#604]
### Expected behaviour
Clicking on a transaction in the "Latest Activity" section of the dashboard should open the details of that transaction

### Actual behaviour
Nothing happens. 0.3.0-rc2

### Steps to reproduce
Click on a transaction in the Dashboard (Latest activity)

**Comment by slaweet** [comment]
Hi @simonmorgenthaler, thank you for reporting this issue. 
We already had an issue to tackle this problem https://github.com/LiskHQ/lisk-hub/issues/593 so I'll mark this one as a duplicate.
The functionality to go to the transaction detail from "Latest Activity" is missing since the initial 0.1.0 version. It took some time to reach a consensus on whether it should open in the tx detail in dashboard, wallet or explorer section. It is planned to be solved in `0.4.0`.

**Comment by slaweet** [comment]
Solved in  #593
