### ISSUE TITLE
One month chart is only displaying two weeks on hub dashboard

### ISSUE THREAD

**Issue by michaeltomasik** [LiskHQ/lisk-hub#800]
### Expected behaviour
Chart showing correct period of time
### Actual behaviour
![39832618-61aa2934-5363-11e8-9c20-df048e045294](https://user-images.githubusercontent.com/7786627/39833250-d4123500-53c9-11e8-8749-d97eca5ddbc3.PNG)

### Steps to reproduce
Go to dashboard, select 1 month on chart

**Comment by slaweet** [comment]
The problem seems to be in the backend. 
Lisk service/explorer doesn't give us enough days of data:
https://service.lisk.io/api/exchanges/getCandles?e=bittrex&d=day
But it provides enough for another exchange:
https://service.lisk.io/api/exchanges/getCandles?e=poloniex&d=day

I think it's just temporary and can also be the other way around. Maybe we can fetch both and get use the one with more returned data.
